name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test run
        run: echo "GitHub Actions is working 🚀"
